// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: msg/msg.proto

package msg

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type MsgID int32

const (
	MsgID_UNKNOWN               MsgID = 0
	MsgID_ConnectID             MsgID = 1
	MsgID_ConnectAckID          MsgID = 2
	MsgID_SubscribeTopicID      MsgID = 3
	MsgID_SubscribeTopicAckID   MsgID = 4
	MsgID_UnsubscribeTopicID    MsgID = 5
	MsgID_UnsubscribeTopicAckID MsgID = 6
	MsgID_HoldMicID             MsgID = 7
	MsgID_HoldMIcAckID          MsgID = 8
	MsgID_ReleaseMicID          MsgID = 9
	MsgID_ReleaseMicAckID       MsgID = 10
	MsgID_DisconnectID          MsgID = 11
	MsgID_DisConnectAckID       MsgID = 12
	MsgID_AudioDataID           MsgID = 13
	MsgID_PingID                MsgID = 14
	MsgID_PongID                MsgID = 15
)

var MsgID_name = map[int32]string{
	0:  "UNKNOWN",
	1:  "ConnectID",
	2:  "ConnectAckID",
	3:  "SubscribeTopicID",
	4:  "SubscribeTopicAckID",
	5:  "UnsubscribeTopicID",
	6:  "UnsubscribeTopicAckID",
	7:  "HoldMicID",
	8:  "HoldMIcAckID",
	9:  "ReleaseMicID",
	10: "ReleaseMicAckID",
	11: "DisconnectID",
	12: "DisConnectAckID",
	13: "AudioDataID",
	14: "PingID",
	15: "PongID",
}

var MsgID_value = map[string]int32{
	"UNKNOWN":               0,
	"ConnectID":             1,
	"ConnectAckID":          2,
	"SubscribeTopicID":      3,
	"SubscribeTopicAckID":   4,
	"UnsubscribeTopicID":    5,
	"UnsubscribeTopicAckID": 6,
	"HoldMicID":             7,
	"HoldMIcAckID":          8,
	"ReleaseMicID":          9,
	"ReleaseMicAckID":       10,
	"DisconnectID":          11,
	"DisConnectAckID":       12,
	"AudioDataID":           13,
	"PingID":                14,
	"PongID":                15,
}

func (x MsgID) String() string {
	return proto.EnumName(MsgID_name, int32(x))
}

func (MsgID) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_d0f0a1b324c95b77, []int{0}
}

type Msg struct {
	Version              int32      `protobuf:"zigzag32,1,opt,name=version,proto3" json:"version,omitempty"`
	Mid                  MsgID      `protobuf:"varint,2,opt,name=mid,proto3,enum=msg.MsgID" json:"mid,omitempty"`
	Uid                  uint32     `protobuf:"varint,3,opt,name=uid,proto3" json:"uid,omitempty"`
	Tid                  uint32     `protobuf:"varint,4,opt,name=tid,proto3" json:"tid,omitempty"`
	Command              *Command   `protobuf:"bytes,5,opt,name=command,proto3" json:"command,omitempty"`
	AudioData            *AudioData `protobuf:"bytes,6,opt,name=audioData,proto3" json:"audioData,omitempty"`
	AckCode              int32      `protobuf:"zigzag32,7,opt,name=ackCode,proto3" json:"ackCode,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *Msg) Reset()         { *m = Msg{} }
func (m *Msg) String() string { return proto.CompactTextString(m) }
func (*Msg) ProtoMessage()    {}
func (*Msg) Descriptor() ([]byte, []int) {
	return fileDescriptor_d0f0a1b324c95b77, []int{0}
}
func (m *Msg) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Msg) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Msg.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Msg) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Msg.Merge(m, src)
}
func (m *Msg) XXX_Size() int {
	return m.Size()
}
func (m *Msg) XXX_DiscardUnknown() {
	xxx_messageInfo_Msg.DiscardUnknown(m)
}

var xxx_messageInfo_Msg proto.InternalMessageInfo

func (m *Msg) GetVersion() int32 {
	if m != nil {
		return m.Version
	}
	return 0
}

func (m *Msg) GetMid() MsgID {
	if m != nil {
		return m.Mid
	}
	return MsgID_UNKNOWN
}

func (m *Msg) GetUid() uint32 {
	if m != nil {
		return m.Uid
	}
	return 0
}

func (m *Msg) GetTid() uint32 {
	if m != nil {
		return m.Tid
	}
	return 0
}

func (m *Msg) GetCommand() *Command {
	if m != nil {
		return m.Command
	}
	return nil
}

func (m *Msg) GetAudioData() *AudioData {
	if m != nil {
		return m.AudioData
	}
	return nil
}

func (m *Msg) GetAckCode() int32 {
	if m != nil {
		return m.AckCode
	}
	return 0
}

type Command struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Command) Reset()         { *m = Command{} }
func (m *Command) String() string { return proto.CompactTextString(m) }
func (*Command) ProtoMessage()    {}
func (*Command) Descriptor() ([]byte, []int) {
	return fileDescriptor_d0f0a1b324c95b77, []int{1}
}
func (m *Command) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Command) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Command.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Command) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Command.Merge(m, src)
}
func (m *Command) XXX_Size() int {
	return m.Size()
}
func (m *Command) XXX_DiscardUnknown() {
	xxx_messageInfo_Command.DiscardUnknown(m)
}

var xxx_messageInfo_Command proto.InternalMessageInfo

type AudioData struct {
	Id                   int32    `protobuf:"zigzag32,1,opt,name=id,proto3" json:"id,omitempty"`
	Tpye                 int32    `protobuf:"zigzag32,2,opt,name=tpye,proto3" json:"tpye,omitempty"`
	Timestamp            uint64   `protobuf:"varint,5,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Data                 []byte   `protobuf:"bytes,6,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AudioData) Reset()         { *m = AudioData{} }
func (m *AudioData) String() string { return proto.CompactTextString(m) }
func (*AudioData) ProtoMessage()    {}
func (*AudioData) Descriptor() ([]byte, []int) {
	return fileDescriptor_d0f0a1b324c95b77, []int{2}
}
func (m *AudioData) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *AudioData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_AudioData.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *AudioData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AudioData.Merge(m, src)
}
func (m *AudioData) XXX_Size() int {
	return m.Size()
}
func (m *AudioData) XXX_DiscardUnknown() {
	xxx_messageInfo_AudioData.DiscardUnknown(m)
}

var xxx_messageInfo_AudioData proto.InternalMessageInfo

func (m *AudioData) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *AudioData) GetTpye() int32 {
	if m != nil {
		return m.Tpye
	}
	return 0
}

func (m *AudioData) GetTimestamp() uint64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

func (m *AudioData) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

func init() {
	proto.RegisterEnum("msg.MsgID", MsgID_name, MsgID_value)
	proto.RegisterType((*Msg)(nil), "msg.Msg")
	proto.RegisterType((*Command)(nil), "msg.Command")
	proto.RegisterType((*AudioData)(nil), "msg.AudioData")
}

func init() { proto.RegisterFile("msg/msg.proto", fileDescriptor_d0f0a1b324c95b77) }

var fileDescriptor_d0f0a1b324c95b77 = []byte{
	// 430 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x5c, 0x92, 0x5d, 0x8a, 0xdb, 0x30,
	0x10, 0xc7, 0x57, 0x76, 0x12, 0xd7, 0x93, 0x2f, 0xed, 0x6c, 0x3f, 0x5c, 0x58, 0x42, 0xc8, 0x43,
	0x09, 0xa5, 0x6c, 0x61, 0x7b, 0x82, 0x6d, 0xf4, 0x50, 0x53, 0x92, 0x16, 0xb5, 0x4b, 0x9f, 0x1d,
	0x4b, 0x18, 0xb1, 0x6b, 0x2b, 0x44, 0x4a, 0xa1, 0x37, 0xe9, 0x2d, 0x7a, 0x8d, 0x3e, 0xb6, 0x37,
	0x28, 0xe9, 0x45, 0x16, 0xc9, 0x76, 0xc2, 0xe6, 0x6d, 0xe6, 0xe7, 0xdf, 0x88, 0xff, 0x0c, 0x86,
	0x61, 0x69, 0x8a, 0xb7, 0xa5, 0x29, 0xae, 0x36, 0x5b, 0x6d, 0x35, 0x86, 0xa5, 0x29, 0x66, 0x7f,
	0x09, 0x84, 0x4b, 0x53, 0x60, 0x02, 0xd1, 0x77, 0xb9, 0x35, 0x4a, 0x57, 0x09, 0x99, 0x92, 0xf9,
	0x39, 0x6f, 0x5b, 0xbc, 0x84, 0xb0, 0x54, 0x22, 0x09, 0xa6, 0x64, 0x3e, 0xba, 0x86, 0x2b, 0x37,
	0xbf, 0x34, 0x45, 0xca, 0xb8, 0xc3, 0x48, 0x21, 0xdc, 0x29, 0x91, 0x84, 0x53, 0x32, 0x1f, 0x72,
	0x57, 0x3a, 0x62, 0x95, 0x48, 0x3a, 0x35, 0xb1, 0x4a, 0xe0, 0x2b, 0x88, 0x72, 0x5d, 0x96, 0x59,
	0x25, 0x92, 0xee, 0x94, 0xcc, 0xfb, 0xd7, 0x03, 0xff, 0xca, 0xa2, 0x66, 0xbc, 0xfd, 0x88, 0x6f,
	0x20, 0xce, 0x76, 0x42, 0x69, 0x96, 0xd9, 0x2c, 0xe9, 0x79, 0x73, 0xe4, 0xcd, 0x9b, 0x96, 0xf2,
	0xa3, 0xe0, 0x12, 0x67, 0xf9, 0xdd, 0x42, 0x0b, 0x99, 0x44, 0x75, 0xe2, 0xa6, 0x9d, 0xc5, 0x10,
	0x35, 0x6f, 0xcf, 0x32, 0x88, 0x0f, 0xc3, 0x38, 0x82, 0x40, 0x89, 0x66, 0xbd, 0x40, 0x09, 0x44,
	0xe8, 0xd8, 0xcd, 0x0f, 0xe9, 0x57, 0x3b, 0xe7, 0xbe, 0xc6, 0x4b, 0x88, 0xad, 0x2a, 0xa5, 0xb1,
	0x59, 0xb9, 0xf1, 0x69, 0x3b, 0xfc, 0x08, 0xdc, 0x84, 0x68, 0xc3, 0x0d, 0xb8, 0xaf, 0x5f, 0xff,
	0x0a, 0xa0, 0xeb, 0x0f, 0x82, 0x7d, 0x88, 0x6e, 0x57, 0x1f, 0x57, 0x9f, 0xbe, 0xad, 0xe8, 0x19,
	0x0e, 0x21, 0x5e, 0xe8, 0xaa, 0x92, 0xb9, 0x4d, 0x19, 0x25, 0x48, 0x61, 0xd0, 0xb4, 0x37, 0xf9,
	0x5d, 0xca, 0x68, 0x80, 0x4f, 0x81, 0x7e, 0xd9, 0xad, 0x4d, 0xbe, 0x55, 0x6b, 0xf9, 0x55, 0x6f,
	0x54, 0x9e, 0x32, 0x1a, 0xe2, 0x0b, 0xb8, 0x78, 0x4c, 0x6b, 0xbd, 0x83, 0xcf, 0x01, 0x6f, 0x2b,
	0x73, 0x3a, 0xd0, 0xc5, 0x97, 0xf0, 0xec, 0x94, 0xd7, 0x23, 0x3d, 0x17, 0xe1, 0x83, 0xbe, 0x17,
	0x4b, 0x6f, 0x46, 0x2e, 0x82, 0x6f, 0xd3, 0x46, 0x78, 0xe2, 0x08, 0x97, 0xf7, 0x32, 0x33, 0xb2,
	0x76, 0x62, 0xbc, 0x80, 0xf1, 0x91, 0xd4, 0x1a, 0x38, 0x8d, 0x29, 0x93, 0x1f, 0xb6, 0xe9, 0x3b,
	0x8d, 0x29, 0xf3, 0x68, 0xa1, 0x01, 0x8e, 0xa1, 0x7f, 0xb8, 0x75, 0xca, 0xe8, 0x10, 0x01, 0x7a,
	0x9f, 0x55, 0x55, 0xa4, 0x8c, 0x8e, 0x7c, 0xad, 0x7d, 0x3d, 0x7e, 0x4f, 0x7f, 0xef, 0x27, 0xe4,
	0xcf, 0x7e, 0x42, 0xfe, 0xed, 0x27, 0xe4, 0xe7, 0xff, 0xc9, 0xd9, 0xba, 0xe7, 0xff, 0xc8, 0x77,
	0x0f, 0x01, 0x00, 0x00, 0xff, 0xff, 0x31, 0x92, 0x6f, 0x08, 0xa2, 0x02, 0x00, 0x00,
}

func (m *Msg) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Msg) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Msg) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.XXX_unrecognized != nil {
		i -= len(m.XXX_unrecognized)
		copy(dAtA[i:], m.XXX_unrecognized)
	}
	if m.AckCode != 0 {
		i = encodeVarintMsg(dAtA, i, uint64((uint32(m.AckCode)<<1)^uint32((m.AckCode>>31))))
		i--
		dAtA[i] = 0x38
	}
	if m.AudioData != nil {
		{
			size, err := m.AudioData.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintMsg(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x32
	}
	if m.Command != nil {
		{
			size, err := m.Command.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintMsg(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x2a
	}
	if m.Tid != 0 {
		i = encodeVarintMsg(dAtA, i, uint64(m.Tid))
		i--
		dAtA[i] = 0x20
	}
	if m.Uid != 0 {
		i = encodeVarintMsg(dAtA, i, uint64(m.Uid))
		i--
		dAtA[i] = 0x18
	}
	if m.Mid != 0 {
		i = encodeVarintMsg(dAtA, i, uint64(m.Mid))
		i--
		dAtA[i] = 0x10
	}
	if m.Version != 0 {
		i = encodeVarintMsg(dAtA, i, uint64((uint32(m.Version)<<1)^uint32((m.Version>>31))))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *Command) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Command) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Command) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.XXX_unrecognized != nil {
		i -= len(m.XXX_unrecognized)
		copy(dAtA[i:], m.XXX_unrecognized)
	}
	return len(dAtA) - i, nil
}

func (m *AudioData) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *AudioData) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *AudioData) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.XXX_unrecognized != nil {
		i -= len(m.XXX_unrecognized)
		copy(dAtA[i:], m.XXX_unrecognized)
	}
	if len(m.Data) > 0 {
		i -= len(m.Data)
		copy(dAtA[i:], m.Data)
		i = encodeVarintMsg(dAtA, i, uint64(len(m.Data)))
		i--
		dAtA[i] = 0x32
	}
	if m.Timestamp != 0 {
		i = encodeVarintMsg(dAtA, i, uint64(m.Timestamp))
		i--
		dAtA[i] = 0x28
	}
	if m.Tpye != 0 {
		i = encodeVarintMsg(dAtA, i, uint64((uint32(m.Tpye)<<1)^uint32((m.Tpye>>31))))
		i--
		dAtA[i] = 0x10
	}
	if m.Id != 0 {
		i = encodeVarintMsg(dAtA, i, uint64((uint32(m.Id)<<1)^uint32((m.Id>>31))))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func encodeVarintMsg(dAtA []byte, offset int, v uint64) int {
	offset -= sovMsg(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *Msg) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Version != 0 {
		n += 1 + sozMsg(uint64(m.Version))
	}
	if m.Mid != 0 {
		n += 1 + sovMsg(uint64(m.Mid))
	}
	if m.Uid != 0 {
		n += 1 + sovMsg(uint64(m.Uid))
	}
	if m.Tid != 0 {
		n += 1 + sovMsg(uint64(m.Tid))
	}
	if m.Command != nil {
		l = m.Command.Size()
		n += 1 + l + sovMsg(uint64(l))
	}
	if m.AudioData != nil {
		l = m.AudioData.Size()
		n += 1 + l + sovMsg(uint64(l))
	}
	if m.AckCode != 0 {
		n += 1 + sozMsg(uint64(m.AckCode))
	}
	if m.XXX_unrecognized != nil {
		n += len(m.XXX_unrecognized)
	}
	return n
}

func (m *Command) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.XXX_unrecognized != nil {
		n += len(m.XXX_unrecognized)
	}
	return n
}

func (m *AudioData) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Id != 0 {
		n += 1 + sozMsg(uint64(m.Id))
	}
	if m.Tpye != 0 {
		n += 1 + sozMsg(uint64(m.Tpye))
	}
	if m.Timestamp != 0 {
		n += 1 + sovMsg(uint64(m.Timestamp))
	}
	l = len(m.Data)
	if l > 0 {
		n += 1 + l + sovMsg(uint64(l))
	}
	if m.XXX_unrecognized != nil {
		n += len(m.XXX_unrecognized)
	}
	return n
}

func sovMsg(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozMsg(x uint64) (n int) {
	return sovMsg(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *Msg) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowMsg
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Msg: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Msg: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Version", wireType)
			}
			var v int32
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMsg
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			v = int32((uint32(v) >> 1) ^ uint32(((v&1)<<31)>>31))
			m.Version = v
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Mid", wireType)
			}
			m.Mid = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMsg
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Mid |= MsgID(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Uid", wireType)
			}
			m.Uid = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMsg
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Uid |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Tid", wireType)
			}
			m.Tid = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMsg
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Tid |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Command", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMsg
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthMsg
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthMsg
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Command == nil {
				m.Command = &Command{}
			}
			if err := m.Command.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field AudioData", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMsg
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthMsg
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthMsg
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.AudioData == nil {
				m.AudioData = &AudioData{}
			}
			if err := m.AudioData.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 7:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field AckCode", wireType)
			}
			var v int32
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMsg
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			v = int32((uint32(v) >> 1) ^ uint32(((v&1)<<31)>>31))
			m.AckCode = v
		default:
			iNdEx = preIndex
			skippy, err := skipMsg(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthMsg
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthMsg
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.XXX_unrecognized = append(m.XXX_unrecognized, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *Command) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowMsg
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Command: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Command: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipMsg(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthMsg
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthMsg
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.XXX_unrecognized = append(m.XXX_unrecognized, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *AudioData) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowMsg
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: AudioData: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: AudioData: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Id", wireType)
			}
			var v int32
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMsg
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			v = int32((uint32(v) >> 1) ^ uint32(((v&1)<<31)>>31))
			m.Id = v
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Tpye", wireType)
			}
			var v int32
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMsg
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			v = int32((uint32(v) >> 1) ^ uint32(((v&1)<<31)>>31))
			m.Tpye = v
		case 5:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Timestamp", wireType)
			}
			m.Timestamp = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMsg
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Timestamp |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Data", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMsg
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthMsg
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthMsg
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Data = append(m.Data[:0], dAtA[iNdEx:postIndex]...)
			if m.Data == nil {
				m.Data = []byte{}
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipMsg(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthMsg
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthMsg
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.XXX_unrecognized = append(m.XXX_unrecognized, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipMsg(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowMsg
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowMsg
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
			return iNdEx, nil
		case 1:
			iNdEx += 8
			return iNdEx, nil
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowMsg
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthMsg
			}
			iNdEx += length
			if iNdEx < 0 {
				return 0, ErrInvalidLengthMsg
			}
			return iNdEx, nil
		case 3:
			for {
				var innerWire uint64
				var start int = iNdEx
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return 0, ErrIntOverflowMsg
					}
					if iNdEx >= l {
						return 0, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					innerWire |= (uint64(b) & 0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				innerWireType := int(innerWire & 0x7)
				if innerWireType == 4 {
					break
				}
				next, err := skipMsg(dAtA[start:])
				if err != nil {
					return 0, err
				}
				iNdEx = start + next
				if iNdEx < 0 {
					return 0, ErrInvalidLengthMsg
				}
			}
			return iNdEx, nil
		case 4:
			return iNdEx, nil
		case 5:
			iNdEx += 4
			return iNdEx, nil
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
	}
	panic("unreachable")
}

var (
	ErrInvalidLengthMsg = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowMsg   = fmt.Errorf("proto: integer overflow")
)
